const VALIDATION_REQUEST_NOT_FOUND = 'ERR_VALIDATION_REQUEST_NOT_FOUND';
const VALIDATION_REQUEST_EXPIRED = 'ERR_VALIDATION_REQUEST_EXPIRED';
const FAILED_ADDRESS_VALIDATION = 'ERR_FAILED_ADDRESS_VALIDATION';
const INVALID_SIGNATURE = 'ERR_INVALID_SIGNATURE';
const SIGNATURE_EXPIRED = 'ERR_SIGNATURE_EXPIRED';

module.exports = {
  VALIDATION_REQUEST_NOT_FOUND,
  VALIDATION_REQUEST_EXPIRED,
  FAILED_ADDRESS_VALIDATION,
  INVALID_SIGNATURE,
  SIGNATURE_EXPIRED,
};
