const BLOCK_NOT_FOUND = 'ERR_BLOCK_NOT_FOUND';
const INVALID_BLOCK_HEIGHT = 'ERR_INVALID_BLOCK_HEIGHT';
const INVALID_BLOCK_HASH = 'ERR_INVALID_BLOCK_HASH';
const MISSING_BLOCK_BODY = 'ERR_MISSING_BLOCK_BODY';
const INVALID_CHAIN = 'ERR_INVALID_CHAIN';
const UNKNOWN = 'ERR_UNKNOWN';

module.exports = {
  BLOCK_NOT_FOUND,
  UNKNOWN,
  INVALID_BLOCK_HEIGHT,
  INVALID_BLOCK_HASH,
  MISSING_BLOCK_BODY,
  INVALID_CHAIN,
};
